--- Makefile.old	2016-08-10 20:58:06.000000000 +0100
+++ Makefile	2016-08-10 21:05:13.000000000 +0100
@@ -1287,7 +1287,7 @@
 		\( -name '*.orig' -o -name '*.rej' -o -name '*~' \
 		-o -name '*.bak' -o -name '#*#' -o -name '.*.orig' \
 		-o -name '.*.rej' -o -name '*%'  -o -name 'core' \) \
-		-type f -print | xargs rm -f
+		-type f -print | xargs -s 122880 rm -f
 
 
 # Packaging of the kernel to various formats
@@ -1509,7 +1509,7 @@
 		-o -name '.*.d' -o -name '.*.tmp' -o -name '*.mod.c' \
 		-o -name '*.symtypes' -o -name 'modules.order' \
 		-o -name modules.builtin -o -name '.tmp_*.o.*' \
-		-o -name '*.gcno' \) -type f -print | xargs rm -f
+		-o -name '*.gcno' \) -type f -print | xargs -s 122880 rm -f
 
 # Generate tags for editors
 # ---------------------------------------------------------------------------
